In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import pdfkit as pdf

In [2]:
prob_ = "signed_graphs"
n_ = 60

In [9]:
form_ = "edge1"
method_ = "lp"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

lp1_n60 = pd.DataFrame()
lp1_n60 = pd.concat([lp1_n60, df], ignore_index=True)
lp1_n60.columns = ['instance','bs','time']
#lp1_n60

tab = pd.DataFrame({
    'instance':"lp_default",
    'bs':lp1_n60['bs'].mean(),
    'time':lp1_n60['time'].mean()
    },index=[""]
)

lp1_n60 = pd.concat([lp1_n60,tab])
lp1_n60['instance'] = lp1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
lp1_n60

                              instance   bs   time
0    random_n60_k2_pos30_neg5_err5_1.g  0.0  0.060
1    random_n60_k2_pos30_neg5_err5_2.g  0.0  0.050
2    random_n60_k2_pos30_neg5_err5_3.g  0.0  0.060
3    random_n60_k2_pos30_neg5_err5_4.g  0.0  0.060
4    random_n60_k2_pos30_neg5_err5_5.g  0.0  0.050
..                                 ...  ...    ...
56  random_n60_k5_pos30_neg5_err20_2.g  0.0  0.030
57  random_n60_k5_pos30_neg5_err20_3.g  0.0  0.030
58  random_n60_k5_pos30_neg5_err20_4.g  0.0  0.030
59  random_n60_k5_pos30_neg5_err20_5.g  0.0  0.030
                            lp_default  0.0  0.039

[61 rows x 3 columns]

In [10]:
form_ = "edge1"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"mip1_default",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,23.00,0.000000,11.0400,81.000000,1
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,11.00,0.000000,1.6300,3.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,9.00,0.000000,4.5800,3.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,13.00,0.000000,13.3900,7.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,13.00,0.000000,5.8700,9.000000,1
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,22.00,0.000000,136.7300,4677.000000,1
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,22.00,0.000000,228.0900,15647.000000,1
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,26.00,0.000000,914.6500,37768.000000,1
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,26.00,0.000000,467.8300,16214.000000,1
,mip1_default,23.616667,22.35,0.022833,541.8275,6931.783333,54

In [11]:
form_ = "edge1"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"mip1_presolve0",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.00,3.000000,0.870000,3600.000000,4085.00,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.00,4.000000,0.640000,3600.000000,4220.00,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.00,3.000000,0.670000,3600.000000,3293.00,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.00,3.000000,0.770000,3600.000000,3422.00,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.00,3.000000,0.770000,3600.000000,4572.00,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.00,4.000000,0.820000,3600.000000,26375.00,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.00,4.000000,0.820000,3600.000000,31778.00,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.00,4.000000,0.850000,3600.000000,41100.00,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.00,4.000000,0.850000,3600.000000,16679.00,0
,mip1_presolve0,23.65,3.866667,0.734333,3505.155667,30588.45,3

In [12]:
form_ = "edge1"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_eqcon2_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"mip1_eqcon2_default",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,23.000000,0.000000,22.600,76.000000,1
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,11.000000,0.000000,12.080,3.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,9.000000,0.000000,3.910,3.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,13.000000,0.000000,17.050,3.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,13.000000,0.000000,17.110,9.000000,1
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,22.000000,0.000000,157.310,4540.000000,1
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,22.000000,0.000000,141.470,7924.000000,1
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,26.000000,0.000000,450.980,16425.000000,1
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,26.000000,0.000000,271.600,3721.000000,1
,mip1_eqcon2_default,23.616667,22.566667,0.017833,553.918,3961.533333,56

In [13]:
form_ = "edge1"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_eqcon2_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"mip1_eqcon2_presolve0",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,3.00,0.8700,3600.000000,3431.000000,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,3.00,0.7300,3600.000000,3328.000000,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,4.00,0.5600,3600.000000,3039.000000,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,3.00,0.7700,3600.000000,2321.000000,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,2.00,0.8500,3600.000000,2795.000000,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,3.00,0.8600,3600.000000,14541.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,4.00,0.8200,3600.000000,50699.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,3.00,0.8800,3600.000000,25510.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,3.00,0.8800,3600.000000,11344.000000,0
,mip1_eqcon2_presolve0,23.666667,3.35,0.7745,3541.186167,27123.516667,1

In [8]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 3.00 & 0.87 & 3600.00 & 3431.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 3.00 & 0.73 & 3600.00 & 3328.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 4.00 & 0.56 & 3600.00 & 3039.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 3.00 & 0.77 & 3600.00 & 2321.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 2.00 & 0.85 & 3600.00 & 2795.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 2.00 & 0.95 & 3600.00 & 2292.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 4.00 & 0.83 & 3600.00 & 4627.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 3.00 & 0.91 & 3600.00 & 2875.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 2.00 & 0.94 & 3600.00 & 1777.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 2.00 & 0.92 & 3600.00 & 1756.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 2.00 & 0.97 & 3600.00 & 4578.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 2.00 & 0.96 & 3600.00 & 2438.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 2.00 & 0.97 & 3600.00 & 1645.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 2.00 & 0.97 & 3600.00 & 1913.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 2.00 & 0.96 & 3600.00 & 2310.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 5.00 & 0.62 & 3600.00 & 29574.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 3.00 & 0.67 & 3600.00 & 17550.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 6.00 & 0.57 & 3600.00 & 34470.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 3.00 & 0.80 & 3600.00 & 4707.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 4.00 & 0.50 & 3600.00 & 28904.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 3.00 & 0.86 & 3600.00 & 20031.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 3.00 & 0.85 & 3600.00 & 9862.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 5.00 & 0.75 & 3600.00 & 27086.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 2.00 & 0.93 & 3600.00 & 4180.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 4.00 & 0.79 & 3600.00 & 12028.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 2.00 & 0.95 & 3600.00 & 7369.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 3.00 & 0.91 & 3600.00 & 7659.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 3.00 & 0.92 & 3600.01 & 10202.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 2.00 & 0.96 & 3600.01 & 3818.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 3.00 & 0.92 & 3600.00 & 9129.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 4.00 & 0.56 & 3600.00 & 20247.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 4.00 & 0.43 & 3600.00 & 269144.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 4.00 & 0.56 & 3600.00 & 31434.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 3.00 & 0.81 & 3600.00 & 20142.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 5.00 & 0.62 & 3600.00 & 55818.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 4.00 & 0.76 & 3600.00 & 33325.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 5.00 & 0.62 & 3600.00 & 52798.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 3.00 & 0.84 & 3600.00 & 9629.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 3.00 & 0.85 & 3600.00 & 13897.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 4.00 & 0.78 & 3600.00 & 12796.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 3.00 & 0.89 & 3600.00 & 11008.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 3.00 & 0.90 & 3600.00 & 20504.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 3.00 & 0.91 & 3600.00 & 14054.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 3.00 & 0.90 & 3600.00 & 13995.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 4.00 & 0.88 & 3600.00 & 11348.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 4.00 & 0.64 & 3600.00 & 120240.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 4.00 & 0.00 & 71.15 & 6055.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 5.00 & 0.50 & 3600.00 & 88128.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 4.00 & 0.60 & 3600.00 & 105884.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 4.00 & 0.33 & 3600.00 & 98609.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 3.00 & 0.83 & 3600.00 & 71082.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 5.00 & 0.58 & 3600.00 & 29550.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 4.00 & 0.78 & 3600.00 & 49912.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 4.00 & 0.69 & 3600.00 & 50430.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 4.00 & 0.73 & 3600.00 & 19758.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 3.00 & 0.88 & 3600.00 & 27836.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 3.00 & 0.86 & 3600.00 & 14541.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 4.00 & 0.82 & 3600.00 & 50699.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 3.00 & 0.88 & 3600.00 & 25510.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 3.00 & 0.88 & 3600.00 & 11344.00 & 0 \\
resume & 3.35 & 0.77 & 3541.19 & 27123.52 & 1 \\
\bottomrule
\end{tabular}