In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import pdfkit as pdf

In [7]:
prob_ = "signed_graphs"
n_ = 60

In [8]:
form_ = "edge2"
method_ = "lp"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

lp2_n60 = pd.DataFrame()
lp2_n60 = pd.concat([lp2_n60, df], ignore_index=True)
lp2_n60.columns = ['instance','bs','time']
#lp2_n60

tab = pd.DataFrame({
    'instance':"lp2_default",
    'bs':lp2_n60['bs'].mean(),
    'time':lp2_n60['time'].mean()
    },index=[""]
)

lp2_n60 = pd.concat([lp2_n60,tab])
lp2_n60['instance'] = lp2_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
lp2_n60

                              instance   bs      time
0    random_n60_k2_pos30_neg5_err5_1.g  0.0  1.350000
1    random_n60_k2_pos30_neg5_err5_2.g  0.0  1.290000
2    random_n60_k2_pos30_neg5_err5_3.g  0.0  1.430000
3    random_n60_k2_pos30_neg5_err5_4.g  0.0  1.480000
4    random_n60_k2_pos30_neg5_err5_5.g  0.0  1.290000
..                                 ...  ...       ...
56  random_n60_k5_pos30_neg5_err20_2.g  0.0  0.510000
57  random_n60_k5_pos30_neg5_err20_3.g  0.0  0.440000
58  random_n60_k5_pos30_neg5_err20_4.g  0.0  0.470000
59  random_n60_k5_pos30_neg5_err20_5.g  0.0  0.580000
                           lp2_default  0.0  0.838167

[61 rows x 3 columns]

In [9]:
form_ = "edge2"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip2_n60 = pd.DataFrame()
mip2_n60 = pd.concat([mip2_n60, df], ignore_index=True)
mip2_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip2_n60

tab = pd.DataFrame({
    'instance':"mip2_default",
    'bb':mip2_n60['bb'].mean(),
    'bs':mip2_n60['bs'].mean(),
    'gap':mip2_n60['gap'].mean(),
    'time':mip2_n60['time'].mean(),
    'nodes':mip2_n60['nodes'].mean(),
    'opt':mip2_n60['opt'].sum()
    },index=[""]
)

mip2_n60 = pd.concat([mip2_n60,tab])
mip2_n60['instance'] = mip2_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip2_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,8.000000,0.650000,3600.120000,733.000000,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,11.000000,0.000000,2493.730000,1238.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,9.000000,0.000000,2077.130000,1791.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,13.000000,0.000000,2627.530000,852.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,9.000000,0.310000,3600.980000,1010.000000,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,24.000000,5.000000,0.790000,3600.110000,1299.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,5.000000,0.770000,3600.670000,1423.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,27.000000,8.000000,0.700000,3600.010000,26260.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,27.000000,3.000000,0.890000,3600.490000,1230.000000,0
,mip2_default,25.266667,7.783333,0.560667,3379.321167,5043.166667,8

In [10]:
form_ = "edge2"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip2_n60 = pd.DataFrame()
mip2_n60 = pd.concat([mip2_n60, df], ignore_index=True)
mip2_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip2_n60_p0

tab = pd.DataFrame({
    'instance':"mip2_presolve0",
    'bb':mip2_n60['bb'].mean(),
    'bs':mip2_n60['bs'].mean(),
    'gap':mip2_n60['gap'].mean(),
    'time':mip2_n60['time'].mean(),
    'nodes':mip2_n60['nodes'].mean(),
    'opt':mip2_n60['opt'].sum()
    },index=[""]
)

mip2_n60 = pd.concat([mip2_n60,tab])
mip2_n60['instance'] = mip2_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip2_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,0.00,1.000000,3600.110000,2659.000000,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,1.00,0.910000,3600.130000,1434.000000,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,1.00,0.890000,3600.010000,1415.000000,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,1.00,0.920000,3600.100000,1401.000000,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,1.00,0.920000,3600.010000,1889.000000,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,23.000000,1.00,0.960000,3600.000000,19262.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,1.00,0.950000,3600.000000,28953.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,1.00,0.960000,3600.000000,31349.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,1.00,0.960000,3600.010000,11537.000000,0
,mip2_presolve0,25.016667,0.95,0.940167,3600.025833,10395.883333,0

In [11]:
form_ = "edge2"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_eqcon2_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip2_n60 = pd.DataFrame()
mip2_n60 = pd.concat([mip2_n60, df], ignore_index=True)
mip2_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip2_n60

tab = pd.DataFrame({
    'instance':"mip2_eqcon2_default",
    'bb':mip2_n60['bb'].mean(),
    'bs':mip2_n60['bs'].mean(),
    'gap':mip2_n60['gap'].mean(),
    'time':mip2_n60['time'].mean(),
    'nodes':mip2_n60['nodes'].mean(),
    'opt':mip2_n60['opt'].sum()
    },index=[""]
)

mip2_n60 = pd.concat([mip2_n60,tab])
mip2_n60['instance'] = mip2_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip2_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,8.000000,0.650000,3600.060000,1006.000000,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,11.000000,0.000000,1788.420000,967.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,9.000000,0.000000,1551.860000,1543.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,13.000000,0.000000,1840.960000,923.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,13.000000,0.000000,2061.930000,255.000000,1
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,8.000000,0.640000,3600.010000,24317.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,8.000000,0.640000,3600.040000,38944.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,7.000000,0.730000,3600.030000,34725.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,5.000000,0.810000,3600.010000,13132.000000,0
,mip2_eqcon2_default,24.683333,7.783333,0.550167,3231.730167,7177.183333,10

In [12]:
form_ = "edge2"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_eqcon2_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip2_n60 = pd.DataFrame()
mip2_n60 = pd.concat([mip2_n60, df], ignore_index=True)
mip2_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip2_n60

tab = pd.DataFrame({
    'instance':"mip2_eqcon2_presolve0",
    'bb':mip2_n60['bb'].mean(),
    'bs':mip2_n60['bs'].mean(),
    'gap':mip2_n60['gap'].mean(),
    'time':mip2_n60['time'].mean(),
    'nodes':mip2_n60['nodes'].mean(),
    'opt':mip2_n60['opt'].sum()
    },index=[""]
)

mip2_n60 = pd.concat([mip2_n60,tab])
mip2_n60['instance'] = mip2_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip2_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,1.000000,0.9600,3600.010,2011.000000,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,1.000000,0.9100,3600.010,1464.000000,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,1.000000,0.8900,3600.030,1201.000000,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,1.000000,0.9200,3600.130,1494.000000,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,1.000000,0.9200,3600.130,1555.000000,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,1.000000,0.9500,3600.030,25422.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,23.000000,1.000000,0.9600,3600.000,38469.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,1.000000,0.9600,3600.000,36099.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,1.000000,0.9600,3600.020,15370.000000,0
,mip2_eqcon2_presolve0,23.883333,0.966667,0.9435,3600.023,12213.166667,0

In [8]:
mip2_n60['instance'] = mip2_n60['instance'].str.replace('_','\_') 
print(mip2_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 1.00 & 0.96 & 3600.01 & 2011.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 1.00 & 0.91 & 3600.01 & 1464.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 1.00 & 0.89 & 3600.03 & 1201.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 1.00 & 0.92 & 3600.13 & 1494.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 1.00 & 0.92 & 3600.13 & 1555.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 1.00 & 0.97 & 3600.05 & 1706.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 1.00 & 0.96 & 3600.06 & 1375.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 1.00 & 0.97 & 3600.06 & 1780.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 1.00 & 0.97 & 3600.14 & 1180.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 1.00 & 0.96 & 3600.01 & 1880.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 1.00 & 0.98 & 3600.02 & 3237.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 1.00 & 0.98 & 3600.01 & 2992.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 0.00 & 1.00 & 3600.02 & 2610.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 1.00 & 0.99 & 3600.02 & 2754.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 1.00 & 0.98 & 3600.02 & 2425.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 1.00 & 0.92 & 3600.07 & 5500.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 1.00 & 0.89 & 3600.01 & 4453.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 1.00 & 0.93 & 3600.03 & 5257.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 1.00 & 0.93 & 3600.02 & 4646.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 1.00 & 0.88 & 3600.02 & 5487.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 1.00 & 0.95 & 3600.06 & 7990.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 1.00 & 0.95 & 3600.01 & 6677.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 1.00 & 0.95 & 3600.01 & 8766.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 1.00 & 0.96 & 3600.01 & 6043.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 1.00 & 0.95 & 3600.03 & 6667.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 1.00 & 0.98 & 3600.01 & 6709.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 1.00 & 0.97 & 3600.01 & 9591.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 1.00 & 0.97 & 3600.02 & 8469.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 1.00 & 0.98 & 3600.01 & 5681.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 1.00 & 0.97 & 3600.01 & 10996.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 1.00 & 0.89 & 3600.03 & 14347.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 0.00 & 1.00 & 3600.05 & 12703.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 1.00 & 0.89 & 3600.03 & 8310.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 1.00 & 0.94 & 3600.01 & 18084.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 1.00 & 0.92 & 3600.00 & 15632.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 1.00 & 0.94 & 3600.00 & 15013.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 1.00 & 0.92 & 3600.01 & 12280.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 1.00 & 0.95 & 3600.01 & 12690.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 1.00 & 0.95 & 3600.01 & 15634.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 1.00 & 0.94 & 3600.01 & 10330.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 1.00 & 0.96 & 3600.01 & 20654.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 1.00 & 0.97 & 3600.00 & 16010.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 1.00 & 0.97 & 3600.01 & 16284.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 1.00 & 0.97 & 3600.02 & 16285.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 1.00 & 0.97 & 3600.00 & 13847.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 1.00 & 0.91 & 3600.01 & 28273.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 0.00 & 1.00 & 3600.01 & 17950.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 2.00 & 0.80 & 3600.01 & 26896.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 1.00 & 0.90 & 3600.01 & 25759.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 1.00 & 0.83 & 3600.00 & 18249.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 1.00 & 0.94 & 3600.00 & 34684.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 1.00 & 0.92 & 3600.00 & 21355.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 1.00 & 0.95 & 3600.00 & 27277.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 1.00 & 0.92 & 3600.00 & 15743.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 1.00 & 0.93 & 3600.04 & 19112.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 1.00 & 0.96 & 3600.00 & 31433.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 1.00 & 0.95 & 3600.03 & 25422.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 1.00 & 0.96 & 3600.00 & 38469.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 1.00 & 0.96 & 3600.00 & 36099.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 1.00 & 0.96 & 3600.02 & 15370.00 & 0 \\
resume & 0.97 & 0.94 & 3600.02 & 12213.17 & 0 \\
\bottomrule
\end{tabular}