In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import pdfkit as pdf

In [2]:
prob_ = "signed_graphs"
n_ = 60

In [3]:
form_ = "edge3"
method_ = "lp"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

lp3_n60 = pd.DataFrame()
lp3_n60 = pd.concat([lp3_n60, df], ignore_index=True)
lp3_n60.columns = ['instance','bs','time']
#lp3_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bs':lp3_n60['bs'].mean(),
    'time':lp3_n60['time'].mean()
    },index=[""]
)

lp3_n60 = pd.concat([lp3_n60,tab])
lp3_n60['instance'] = lp3_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
lp3_n60

                              instance   bs    time
0    random_n60_k2_pos30_neg5_err5_1.g  0.0  1.5000
1    random_n60_k2_pos30_neg5_err5_2.g  0.0  1.4300
2    random_n60_k2_pos30_neg5_err5_3.g  0.0  1.7000
3    random_n60_k2_pos30_neg5_err5_4.g  0.0  1.6100
4    random_n60_k2_pos30_neg5_err5_5.g  0.0  1.4000
..                                 ...  ...     ...
56  random_n60_k5_pos30_neg5_err20_2.g  0.0  0.6100
57  random_n60_k5_pos30_neg5_err20_3.g  0.0  0.5000
58  random_n60_k5_pos30_neg5_err20_4.g  0.0  0.5400
59  random_n60_k5_pos30_neg5_err20_5.g  0.0  0.6600
                                resume  0.0  0.9345

[61 rows x 3 columns]

In [4]:
form_ = "edge3"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip3_n60 = pd.DataFrame()
mip3_n60 = pd.concat([mip3_n60, df], ignore_index=True)
mip3_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip3_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bb':mip3_n60['bb'].mean(),
    'bs':mip3_n60['bs'].mean(),
    'gap':mip3_n60['gap'].mean(),
    'time':mip3_n60['time'].mean(),
    'nodes':mip3_n60['nodes'].mean(),
    'opt':mip3_n60['opt'].sum()
    },index=[""]
)

mip3_n60 = pd.concat([mip3_n60,tab])
mip3_n60['instance'] = mip3_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip3_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.00,23.0,0.000000,469.4200,28.000000,1
1,random_n60_k2_pos30_neg5_err5_2.g,11.00,11.0,0.000000,306.6100,7.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.00,9.0,0.000000,307.1600,3.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.00,13.0,0.000000,363.0100,7.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.00,13.0,0.000000,311.1600,9.000000,1
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.00,13.0,0.410000,3600.0100,3552.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.00,13.0,0.410000,3600.6200,1778.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.00,13.0,0.500000,3600.0200,10202.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.00,12.0,0.540000,3600.0100,2307.000000,0
,resume,23.75,17.0,0.173333,1592.4855,953.966667,38

In [5]:
form_ = "edge3"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip3_n60 = pd.DataFrame()
mip3_n60 = pd.concat([mip3_n60, df], ignore_index=True)
mip3_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip3_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bb':mip3_n60['bb'].mean(),
    'bs':mip3_n60['bs'].mean(),
    'gap':mip3_n60['gap'].mean(),
    'time':mip3_n60['time'].mean(),
    'nodes':mip3_n60['nodes'].mean(),
    'opt':mip3_n60['opt'].sum()
    },index=[""]
)

mip3_n60 = pd.concat([mip3_n60,tab])
mip3_n60['instance'] = mip3_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip3_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,1.0,0.960000,3600.140,735.000000,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,2.0,0.820000,3600.030,710.000000,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,2.0,0.780000,3600.030,717.000000,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,0.0,1.000000,3600.020,90.000000,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,1.0,0.920000,3600.020,714.000000,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,23.000000,2.0,0.910000,3600.070,1362.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,2.0,0.910000,3600.000,3207.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,2.0,0.920000,3600.030,1604.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,27.000000,2.0,0.930000,3600.040,1164.000000,0
,resume,24.833333,1.5,0.883167,3547.032,1803.433333,1

In [6]:
form_ = "edge3"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_eqcon2_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip3_n60 = pd.DataFrame()
mip3_n60 = pd.concat([mip3_n60, df], ignore_index=True)
mip3_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip3_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bb':mip3_n60['bb'].mean(),
    'bs':mip3_n60['bs'].mean(),
    'gap':mip3_n60['gap'].mean(),
    'time':mip3_n60['time'].mean(),
    'nodes':mip3_n60['nodes'].mean(),
    'opt':mip3_n60['opt'].sum()
    },index=[""]
)

mip3_n60 = pd.concat([mip3_n60,tab])
mip3_n60['instance'] = mip3_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip3_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,23.00,0.0000,598.280000,37.000000,1
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,11.00,0.0000,411.680000,11.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,9.00,0.0000,337.790000,3.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,13.00,0.0000,385.420000,7.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,13.00,0.0000,416.310000,11.000000,1
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,11.00,0.5000,3600.010000,1039.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,16.00,0.2700,3600.660000,1568.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,12.00,0.5400,3600.010000,3673.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,13.00,0.5000,3600.040000,1231.000000,0
,resume,24.066667,16.25,0.1895,1820.657167,924.116667,38

In [8]:
form_ = "edge3"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_eqcon2_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip3_n60 = pd.DataFrame()
mip3_n60 = pd.concat([mip3_n60, df], ignore_index=True)
mip3_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip3_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bb':mip3_n60['bb'].mean(),
    'bs':mip3_n60['bs'].mean(),
    'gap':mip3_n60['gap'].mean(),
    'time':mip3_n60['time'].mean(),
    'nodes':mip3_n60['nodes'].mean(),
    'opt':mip3_n60['opt'].sum()
    },index=[""]
)

mip3_n60 = pd.concat([mip3_n60,tab])
mip3_n60['instance'] = mip3_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip3_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,0.000000,1.000000,3600.010000,97.00,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,2.000000,0.820000,3600.020000,697.00,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,1.000000,0.890000,3600.020000,674.00,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,0.000000,1.000000,3600.050000,679.00,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,0.000000,1.000000,3600.020000,613.00,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,2.000000,0.910000,3600.040000,935.00,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,2.000000,0.910000,3600.010000,1738.00,0
58,random_n60_k5_pos30_neg5_err20_4.g,27.000000,2.000000,0.930000,3600.010000,1575.00,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,2.000000,0.920000,3600.010000,998.00,0
,resume,25.966667,1.233333,0.897667,3548.224167,1201.05,1